config/routes.rb
Piatachok::Application.routes.draw do
  devise_for :users

  root :to => "home#index"

  resources :money_operations

  match "settings" => "settings#index"

  resources :invites, only: [:create] do
    member do
      put :accept
      put :reject
    end
  end

  resources :families, only: [:update]

  resources :categories, only: [:index, :create, :update, :destroy]

  resources :reports, only: [:index] do
    collection do
      get :single
    end
  end

end

app/models/category.rb
# encoding: UTF-8
class Category < ActiveRecord::Base

  validates_presence_of :name, :type

  belongs_to :family
  validate :correct_type

  attr_accessible :name, :family_id, :family, :type

  ##
  # Classes for categories:
  #
  #   {SpendCategory}  - categories for spendings (e.g. "Food", "Transport", etc.)
  #   {IncomeCategory} - categories for incomings (e.g. "Salary", "Gift", etc.)
  #   {CreditCategory} - categories for lending or taking on credit
  #   {PlanCategories} - categories for planning the spending or incoming
  #
  TYPES = %w{SpendCategory IncomeCategory CreditCategory PlanCategory}


  class << self
    def for_user(user)
      where("family_id is null or family_id = ?", user.family_id).order(:name)
    end

  end

  private

  ##
  # Validation of type
  #
  def correct_type
    Category::TYPES.include? self.type
  end
end

app/controllers/categories_controller.rb
# encoding: utf-8
class CategoriesController < ApplicationController

  load_and_authorize_resource except: [:index]

  ##
  # Show list of user's categories
  #
  def index
    authorize! :view, Family
    @spend_categories = SpendCategory.where(family_id: current_user.family.id)
    @spend_categories.order("name DESC") if @spend_categories.present?
    @income_categories = IncomeCategory.where(family_id: current_user.family.id)
    @income_categories.order("name DESC") if @income_categories.present?
  end

  ##
  # Create new user's category
  #
  def create
    @category.family = current_user.family
    authorize! :create, @category
    if @category.save!
      flash[:notice] = "Категория успешно добавлена"
    else
      flash[:alert] = "Ошибка добавления категории трат: #{@category.errors.full_messages}"
    end

    respond_to do |format|
      format.html { redirect_to categories_path }
    end
  end

  ##
  # Create new user's category
  #
  def update
    if @category.update_attributes(params[:category])
      flash[:notice] = "Категория успешно изменена"
    else
      flash[:alert] = "Ошибка изменения категории: #{@category.errors.full_messages}"
    end
    respond_to do |format|
      format.html { redirect_to categories_path }
    end
  end

  ##
  # Delete user's category
  #
  def destroy
    if @category.delete
      flash[:notice] = "Категория успешно удалена"
    else
      flash[:alert] = "Ошибка удаления категории: #{@category.errors.full_messages}"
    end

    respond_to do |format|
      format.html { redirect_to categories_path }
    end
  end

end

app/views/categories/index.html.erb
<div class="spend_block">
<h2>Категории трат</h2>
<i>(будут доступны только вашей семье)</i>
<table class="grid">
  <thead>
    <th>Категория</th>
    <th><a href="#" id="add_spend_category" class="button">Добавить</a></th>
  </thead>
  <tbody>
    <tr class="spend_category_row hidden">
      <td colspan="2">
        <%= form_for(:category, html: {id: "spend_category_form"}) do |f| %>
          <%= f.text_field(:name) %>
          <%= f.hidden_field(:type, value: "SpendCategory") %>
          <%= f.submit("Сохранить") %>
        <% end %>
      </td>
    </tr>
  <% if @spend_categories.present? %>
      <% @spend_categories.each do |item| %>
        <tr data-id="<%= item.id %>">
          <td><%= item.name %></td><td><%= link_to "Править", "#", class: "edit_spend_category action_button_min" %> <%= button_to "Удалить", category_path(item), confirm: "Удалить категорию?", method: :delete, class: "action_button_min" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

<div class="income_block">
  <h2>Категории поступлений</h2>
  <i>(будут доступны только вашей семье)</i>
  <table class="grid">
    <thead>
    <th>Категория</th>
    <th><a href="#" id="add_income_category" class="button">Добавить</a></th>
    </thead>
    <tbody>
    <tr class="income_category_row hidden">
      <td colspan="2">
        <%= form_for(:category, html: {id: "income_category_form"}) do |f| %>
          <%= f.text_field(:name) %>
          <%= f.hidden_field(:type, value: "IncomeCategory") %>
          <%= f.submit("Сохранить") %>
        <% end %>
      </td>
    </tr>
    <% if @income_categories.present? %>
      <% @income_categories.each do |item| %>
        <tr data-id="<%= item.id %>">
          <td><%= item.name %></td><td><%= link_to "Править", "#", class: "edit_income_category action_button_min" %> <%= button_to "Удалить", category_path(item), confirm: "Удалить категорию?", method: :delete, class: "action_button_min" %></td>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>