config/routes.rb
Piatachok::Application.routes.draw do
  devise_for :users

  root :to => "home#index"

  resources :money_operations

  match "settings" => "settings#index"

  resources :invites, only: [:create] do
    member do
      put :accept
      put :reject
    end
  end

  resources :families, only: [:update]

  resources :categories, only: [:index, :create, :update, :destroy]

  resources :reports, only: [:index] do
    collection do
      get :single
    end
  end

end

app/controllers/reports_controller.rb
# encoding: utf-8
class ReportsController < ApplicationController

  ##
  # Show list of reports
  #
  def index
  end

  ##
  # Show defined report
  #
  def show

  end

  def single
    @select_period = params[:select_period] || 0
    case @select_period
      when "day"
        @date_from = Date.today
        @date_to = Date.today
      when "month"
        @date_from = Date.today.beginning_of_month
        @date_to = Date.today
      when "year"
        @date_from =Date.today.beginning_of_year
        @date_to = Date.today
      when "other"
        @date_from = params[:day].present?  ? Date.parse(params[:day])  : Date.today
        @date_to =   params[:day2].present? ? Date.parse(params[:day2]) : Date.today
      else
        @date_from = Date.today
        @date_to = Date.today
    end
    @table = Report.single(current_user.family_id, @date_from..@date_to, 1)

    @category_list = []
    if @table[:titles].size > 1
      @table[:titles][1..-1].each do |item|
        @category_list << {item[:id] => item[:name], value: 1}
      end
    else
      MoneyOperation.categories_of_family(current_user.family).each do |item|
        @category_list << {item[:id] => item[:name], value: 1}
      end
    end

    render :show, locals: {report_name: "Простой отчёт", report_type: :single }
  end



end

app/views/reports/_filter.html.erb
<%= render "shared/select_period", select_period: select_period, period: period, title: "Период:", allow_change_end_date: true %>

app/views/reports/_single.html.erb
<table class="grid">
  <thead>
  <tr>
    <% table[:titles].each do |category| %>
      <%= content_tag(:th, category[:name], "data-category_id" => category[:id]) %>
    <% end %>
  </tr>
  </thead>
  <tbody>
    <% table[:rows].each do |row| %>
      <tr>
        <%= content_tag(:td, row[0]) %>
        <% row[1..-1].each_with_index do |column, index| %>
          <% category = table[:titles][index+1] %>
          <% class_name = "" %>
          <% class_name = "income" if category[:type] == "IncomeCategory" %>
          <% class_name = "spend" if category[:type] == "SpendCategory" %>
          <%= content_tag(:td, MoneyOperation.sum_formatted(column), class: "align_right #{class_name}", "data-category_id" => category[:id]) %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/index.html.erb
<div class="main_content">
  <%= link_to "Простой отчёт", single_reports_path, class: "report_button" %>
  <%= link_to "Сравнительный отчёт", "#", class: "report_button" %>
  <%= link_to "Динамический отчёт", "#", class: "report_button" %>
</div>

app/views/reports/show.html.erb
<% report_path = single_reports_path if report_type == :single %>

<div class="top_panel">
  <%= content_tag(:h1, report_name) %>
  <%= form_for report_path, id: "report_params", method: "get" do |f| %>
    <%= render "filter", select_period: @select_period, period: @date_from..@date_to %>
    <div class="inline">
      <div class="inline-block">
        <%= render "shared/check_combo_box", name: :categories, list: @category_list %>
      </div>
      <%= f.submit "Показать", class: "action_button" %>
    </div>
  <% end %>

</div>

<% if @table[:rows].present? %>
  <%= render report_type.to_s, table: @table if report_path == single_reports_path %>
<% else %>

<% end %>