config/routes.rb
Piatachok::Application.routes.draw do
  devise_for :users

  root :to => "home#index"

  resources :money_operations

  match "settings" => "settings#index"

  resources :invites, only: [:create] do
    member do
      put :accept
      put :reject
    end
  end

  resources :families, only: [:update]

  resources :categories, only: [:index, :create, :update, :destroy]

  resources :reports, only: [:index] do
    collection do
      get :single
    end
  end

end

app/views/layouts/_blitz_info.html.erb
<% if current_user.present? && current_user.family.present? %>
  <div id="blitz_info">
    <%= content_tag :b, current_user.family.name %><br>
    <table>
      <tr><td>Баланс семьи:</td><td class="align_right"><%= content_tag(:b, family_balance) %></td></tr>
      <tr><td>Траты за день:</td><td class="align_right"><%= content_tag(:b, family_dayly_spent) %></td></tr>
      <tr><td>Траты за месяц:</td><td class="align_right"><%= content_tag(:b, family_monthly_spent) %></td></tr>
      <tr><td>Приход за месяц:</td><td class="align_right"><%= content_tag(:b, family_monthly_income) %></td></tr>
    </table>
  </div>
<% end %>

app/views/layouts/_family_members.html.erb
<% if current_user.present? && current_user.family.present? %>
  <div id="blitz_info">
    <b>Члены семьи:</b><br>
    <%= current_user.relatives(true).map(&:show_name).join("<br>").html_safe %>
  </div>
<% end %>

app/views/layouts/_menu.html.erb
<nav id="control" class="menu">
  <ul>
    <% if current_user.blank? %>
      <%= content_tag(:li, link_to("Войти", new_user_session_path)) %>
      <%= content_tag(:li, link_to("Регистрация", new_user_registration_path)) %>
    <% else %>
      <li><a href="#" class="openable">+Траты</a></li>
      <ul class="submenu hidden">
        <li><%= link_to "Новая трата", new_money_operation_path(money_operation: {is_spent: true}) %></li>
        <li><%= link_to "Список трат", money_operations_path(operation_type: { spend: true }) %></li>
      </ul>
      <li><a href="#" class="openable">+Поступления</a></li>
      <ul class="submenu hidden">
        <li><%= link_to "Новое поступление", new_money_operation_path(money_operation: {is_spent: false}) %></li>
        <li><%= link_to "Список поступлений", money_operations_path(operation_type: { income: true }) %></li>
      </ul>
      <li><%= link_to "Отчёты", reports_path %></li>
      <li><a href="#" class="openable">+Настройки</a></li>
      <ul class="submenu hidden">
        <li><%= link_to "Семья", settings_path %></li>
        <li><%= link_to "Категории", categories_path %></li>
      </ul>
    <% end %>
  </ul>
</nav>

app/views/layouts/_user_info.html.erb
<% if current_user.present? %>
  <nav id="user_info" class="menu">
    <%= content_tag(:b, current_user.show_name) %><br><br>
    <ul>
      <%= content_tag(:li, link_to("Изменить данные", edit_user_registration_path)) %>
      <%= content_tag(:li, link_to("Выйти", destroy_user_session_path, method: :delete)) %>
    </ul>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Пятачок</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="main"><a href="/"><img src="/images/logo_head.jpg"></a></header>

  <nav id="menu_container">
    <%= render "layouts/menu" %><br>

    <%= render "layouts/user_info" %><br>

    <%= render "layouts/blitz_info" %>

    <%= render "layouts/family_members" %>
  </nav>

  <section class="main_content">
    <%= show_flash %>

    <%= yield %>
  </section>

  <aside class="aside_right">

  </aside>

</body>
</html>